export const COUNTRIES = [
  { code: "AF", name: "Afghanistan", currency: "AFN", symbol: "؋", phoneCode: "93", timezone: "Asia/Kabul" },
  { code: "AL", name: "Albania", currency: "ALL", symbol: "L", phoneCode: "355", timezone: "Europe/Tirane" },
  { code: "DZ", name: "Algeria", currency: "DZD", symbol: "د.ج", phoneCode: "213", timezone: "Africa/Algiers" },
  { code: "AD", name: "Andorra", currency: "EUR", symbol: "€", phoneCode: "376", timezone: "Europe/Andorra" },
  { code: "AO", name: "Angola", currency: "AOA", symbol: "Kz", phoneCode: "244", timezone: "Africa/Luanda" },
  { code: "AR", name: "Argentina", currency: "ARS", symbol: "$", phoneCode: "54", timezone: "America/Argentina/Buenos_Aires" },
  { code: "AM", name: "Armenia", currency: "AMD", symbol: "֏", phoneCode: "374", timezone: "Asia/Yerevan" },
  { code: "AU", name: "Australia", currency: "AUD", symbol: "A$", phoneCode: "61", timezone: "Australia/Sydney" },
  { code: "AT", name: "Austria", currency: "EUR", symbol: "€", phoneCode: "43", timezone: "Europe/Vienna" },
  { code: "AZ", name: "Azerbaijan", currency: "AZN", symbol: "₼", phoneCode: "994", timezone: "Asia/Baku" },
  { code: "BH", name: "Bahrain", currency: "BHD", symbol: ".د.ب", phoneCode: "973", timezone: "Asia/Bahrain" },
  { code: "BD", name: "Bangladesh", currency: "BDT", symbol: "৳", phoneCode: "880", timezone: "Asia/Dhaka" },
  { code: "BY", name: "Belarus", currency: "BYN", symbol: "Br", phoneCode: "375", timezone: "Europe/Minsk" },
  { code: "BE", name: "Belgium", currency: "EUR", symbol: "€", phoneCode: "32", timezone: "Europe/Brussels" },
  { code: "BZ", name: "Belize", currency: "BZD", symbol: "BZ$", phoneCode: "501", timezone: "America/Belize" },
  { code: "BT", name: "Bhutan", currency: "BTN", symbol: "Nu.", phoneCode: "975", timezone: "Asia/Thimphu" },
  { code: "BO", name: "Bolivia", currency: "BOB", symbol: "Bs.", phoneCode: "591", timezone: "America/La_Paz" },
  { code: "BA", name: "Bosnia and Herzegovina", currency: "BAM", symbol: "KM", phoneCode: "387", timezone: "Europe/Sarajevo" },
  { code: "BW", name: "Botswana", currency: "BWP", symbol: "P", phoneCode: "267", timezone: "Africa/Gaborone" },
  { code: "BR", name: "Brazil", currency: "BRL", symbol: "R$", phoneCode: "55", timezone: "America/Sao_Paulo" },
  { code: "BN", name: "Brunei", currency: "BND", symbol: "B$", phoneCode: "673", timezone: "Asia/Brunei" },
  { code: "BG", name: "Bulgaria", currency: "BGN", symbol: "лв", phoneCode: "359", timezone: "Europe/Sofia" },
  { code: "KH", name: "Cambodia", currency: "KHR", symbol: "៛", phoneCode: "855", timezone: "Asia/Phnom_Penh" },
  { code: "CA", name: "Canada", currency: "CAD", symbol: "C$", phoneCode: "1", timezone: "America/Toronto" },
  { code: "CL", name: "Chile", currency: "CLP", symbol: "$", phoneCode: "56", timezone: "America/Santiago" },
  { code: "CN", name: "China", currency: "CNY", symbol: "¥", phoneCode: "86", timezone: "Asia/Shanghai" },
  { code: "CO", name: "Colombia", currency: "COP", symbol: "$", phoneCode: "57", timezone: "America/Bogota" },
  { code: "CR", name: "Costa Rica", currency: "CRC", symbol: "₡", phoneCode: "506", timezone: "America/Costa_Rica" },
  { code: "HR", name: "Croatia", currency: "EUR", symbol: "€", phoneCode: "385", timezone: "Europe/Zagreb" },
  { code: "CU", name: "Cuba", currency: "CUP", symbol: "₱", phoneCode: "53", timezone: "America/Havana" },
  { code: "CY", name: "Cyprus", currency: "EUR", symbol: "€", phoneCode: "357", timezone: "Asia/Nicosia" },
  { code: "CZ", name: "Czech Republic", currency: "CZK", symbol: "Kč", phoneCode: "420", timezone: "Europe/Prague" },
  { code: "DK", name: "Denmark", currency: "DKK", symbol: "kr", phoneCode: "45", timezone: "Europe/Copenhagen" },
  { code: "DO", name: "Dominican Republic", currency: "DOP", symbol: "RD$", phoneCode: "1-809", timezone: "America/Santo_Domingo" },
  { code: "EC", name: "Ecuador", currency: "USD", symbol: "$", phoneCode: "593", timezone: "America/Guayaquil" },
  { code: "EG", name: "Egypt", currency: "EGP", symbol: "£", phoneCode: "20", timezone: "Africa/Cairo" },
  { code: "SV", name: "El Salvador", currency: "USD", symbol: "$", phoneCode: "503", timezone: "America/El_Salvador" },
  { code: "EE", name: "Estonia", currency: "EUR", symbol: "€", phoneCode: "372", timezone: "Europe/Tallinn" },
  { code: "ET", name: "Ethiopia", currency: "ETB", symbol: "Br", phoneCode: "251", timezone: "Africa/Addis_Ababa" },
  { code: "FJ", name: "Fiji", currency: "FJD", symbol: "$", phoneCode: "679", timezone: "Pacific/Fiji" },
  { code: "FI", name: "Finland", currency: "EUR", symbol: "€", phoneCode: "358", timezone: "Europe/Helsinki" },
  { code: "FR", name: "France", currency: "EUR", symbol: "€", phoneCode: "33", timezone: "Europe/Paris" },
  { code: "GE", name: "Georgia", currency: "GEL", symbol: "₾", phoneCode: "995", timezone: "Asia/Tbilisi" },
  { code: "DE", name: "Germany", currency: "EUR", symbol: "€", phoneCode: "49", timezone: "Europe/Berlin" },
  { code: "GH", name: "Ghana", currency: "GHS", symbol: "GH₵", phoneCode: "233", timezone: "Africa/Accra" },
  { code: "GR", name: "Greece", currency: "EUR", symbol: "€", phoneCode: "30", timezone: "Europe/Athens" },
  { code: "GT", name: "Guatemala", currency: "GTQ", symbol: "Q", phoneCode: "502", timezone: "America/Guatemala" },
  { code: "HN", name: "Honduras", currency: "HNL", symbol: "L", phoneCode: "504", timezone: "America/Tegucigalpa" },
  { code: "HK", name: "Hong Kong", currency: "HKD", symbol: "HK$", phoneCode: "852", timezone: "Asia/Hong_Kong" },
  { code: "HU", name: "Hungary", currency: "HUF", symbol: "Ft", phoneCode: "36", timezone: "Europe/Budapest" },
  { code: "IS", name: "Iceland", currency: "ISK", symbol: "kr", phoneCode: "354", timezone: "Atlantic/Reykjavik" },
  { code: "IN", name: "India", currency: "INR", symbol: "₹", phoneCode: "91", timezone: "Asia/Kolkata" },
  { code: "ID", name: "Indonesia", currency: "IDR", symbol: "Rp", phoneCode: "62", timezone: "Asia/Jakarta" },
  { code: "IR", name: "Iran", currency: "IRR", symbol: "﷼", phoneCode: "98", timezone: "Asia/Tehran" },
  { code: "IQ", name: "Iraq", currency: "IQD", symbol: "ع.د", phoneCode: "964", timezone: "Asia/Baghdad" },
  { code: "IE", name: "Ireland", currency: "EUR", symbol: "€", phoneCode: "353", timezone: "Europe/Dublin" },
  { code: "IL", name: "Israel", currency: "ILS", symbol: "₪", phoneCode: "972", timezone: "Asia/Jerusalem" },
  { code: "IT", name: "Italy", currency: "EUR", symbol: "€", phoneCode: "39", timezone: "Europe/Rome" },
  { code: "JM", name: "Jamaica", currency: "JMD", symbol: "J$", phoneCode: "1-876", timezone: "America/Jamaica" },
  { code: "JP", name: "Japan", currency: "JPY", symbol: "¥", phoneCode: "81", timezone: "Asia/Tokyo" },
  { code: "JO", name: "Jordan", currency: "JOD", symbol: "د.ا", phoneCode: "962", timezone: "Asia/Amman" },
  { code: "KZ", name: "Kazakhstan", currency: "KZT", symbol: "₸", phoneCode: "7", timezone: "Asia/Almaty" },
  { code: "KE", name: "Kenya", currency: "KES", symbol: "KSh", phoneCode: "254", timezone: "Africa/Nairobi" },
  { code: "KR", name: "Korea, South", currency: "KRW", symbol: "₩", phoneCode: "82", timezone: "Asia/Seoul" },
  { code: "KW", name: "Kuwait", currency: "KWD", symbol: "د.ك", phoneCode: "965", timezone: "Asia/Kuwait" },
  { code: "LV", name: "Latvia", currency: "EUR", symbol: "€", phoneCode: "371", timezone: "Europe/Riga" },
  { code: "LB", name: "Lebanon", currency: "LBP", symbol: "ل.ل", phoneCode: "961", timezone: "Asia/Beirut" },
  { code: "LY", name: "Libya", currency: "LYD", symbol: "ل.د", phoneCode: "218", timezone: "Africa/Tripoli" },
  { code: "LT", name: "Lithuania", currency: "EUR", symbol: "€", phoneCode: "370", timezone: "Europe/Vilnius" },
  { code: "LU", name: "Luxembourg", currency: "EUR", symbol: "€", phoneCode: "352", timezone: "Europe/Luxembourg" },
  { code: "MY", name: "Malaysia", currency: "MYR", symbol: "RM", phoneCode: "60", timezone: "Asia/Kuala_Lumpur" },
  { code: "MV", name: "Maldives", currency: "MVR", symbol: ".ރ", phoneCode: "960", timezone: "Indian/Maldives" },
  { code: "MT", name: "Malta", currency: "EUR", symbol: "€", phoneCode: "356", timezone: "Europe/Malta" },
  { code: "MX", name: "Mexico", currency: "MXN", symbol: "$", phoneCode: "52", timezone: "America/Mexico_City" },
  { code: "MC", name: "Monaco", currency: "EUR", symbol: "€", phoneCode: "377", timezone: "Europe/Monaco" },
  { code: "MN", name: "Mongolia", currency: "MNT", symbol: "₮", phoneCode: "976", timezone: "Asia/Ulaanbaatar" },
  { code: "ME", name: "Montenegro", currency: "EUR", symbol: "€", phoneCode: "382", timezone: "Europe/Podgorica" },
  { code: "MA", name: "Morocco", currency: "MAD", symbol: "د.م.", phoneCode: "212", timezone: "Africa/Casablanca" },
  { code: "MM", name: "Myanmar", currency: "MMK", symbol: "K", phoneCode: "95", timezone: "Asia/Yangon" },
  { code: "NP", name: "Nepal", currency: "NPR", symbol: "रू", phoneCode: "977", timezone: "Asia/Kathmandu" },
  { code: "NL", name: "Netherlands", currency: "EUR", symbol: "€", phoneCode: "31", timezone: "Europe/Amsterdam" },
  { code: "NZ", name: "New Zealand", currency: "NZD", symbol: "$", phoneCode: "64", timezone: "Pacific/Auckland" },
  { code: "NG", name: "Nigeria", currency: "NGN", symbol: "₦", phoneCode: "234", timezone: "Africa/Lagos" },
  { code: "NO", name: "Norway", currency: "NOK", symbol: "kr", phoneCode: "47", timezone: "Europe/Oslo" },
  { code: "OM", name: "Oman", currency: "OMR", symbol: "ر.ع.", phoneCode: "968", timezone: "Asia/Muscat" },
  { code: "PK", name: "Pakistan", currency: "PKR", symbol: "₨", phoneCode: "92", timezone: "Asia/Karachi" },
  { code: "PA", name: "Panama", currency: "PAB", symbol: "B/.", phoneCode: "507", timezone: "America/Panama" },
  { code: "PY", name: "Paraguay", currency: "PYG", symbol: "₲", phoneCode: "595", timezone: "America/Asuncion" },
  { code: "PE", name: "Peru", currency: "PEN", symbol: "S/.", phoneCode: "51", timezone: "America/Lima" },
  { code: "PH", name: "Philippines", currency: "PHP", symbol: "₱", phoneCode: "63", timezone: "Asia/Manila" },
  { code: "PL", name: "Poland", currency: "PLN", symbol: "zł", phoneCode: "48", timezone: "Europe/Warsaw" },
  { code: "PT", name: "Portugal", currency: "EUR", symbol: "€", phoneCode: "351", timezone: "Europe/Lisbon" },
  { code: "QA", name: "Qatar", currency: "QAR", symbol: "ر.ق", phoneCode: "974", timezone: "Asia/Qatar" },
  { code: "RO", name: "Romania", currency: "RON", symbol: "lei", phoneCode: "40", timezone: "Europe/Bucharest" },
  { code: "RU", name: "Russia", currency: "RUB", symbol: "₽", phoneCode: "7", timezone: "Europe/Moscow" },
  { code: "SA", name: "Saudi Arabia", currency: "SAR", symbol: "ر.س", phoneCode: "966", timezone: "Asia/Riyadh" },
  { code: "RS", name: "Serbia", currency: "RSD", symbol: "din", phoneCode: "381", timezone: "Europe/Belgrade" },
  { code: "SG", name: "Singapore", currency: "SGD", symbol: "S$", phoneCode: "65", timezone: "Asia/Singapore" },
  { code: "SK", name: "Slovakia", currency: "EUR", symbol: "€", phoneCode: "421", timezone: "Europe/Bratislava" },
  { code: "SI", name: "Slovenia", currency: "EUR", symbol: "€", phoneCode: "386", timezone: "Europe/Ljubljana" },
  { code: "ZA", name: "South Africa", currency: "ZAR", symbol: "R", phoneCode: "27", timezone: "Africa/Johannesburg" },
  { code: "ES", name: "Spain", currency: "EUR", symbol: "€", phoneCode: "34", timezone: "Europe/Madrid" },
  { code: "LK", name: "Sri Lanka", currency: "LKR", symbol: "Rs", phoneCode: "94", timezone: "Asia/Colombo" },
  { code: "SE", name: "Sweden", currency: "SEK", symbol: "kr", phoneCode: "46", timezone: "Europe/Stockholm" },
  { code: "CH", name: "Switzerland", currency: "CHF", symbol: "CHF", phoneCode: "41", timezone: "Europe/Zurich" },
  { code: "TW", name: "Taiwan", currency: "TWD", symbol: "NT$", phoneCode: "886", timezone: "Asia/Taipei" },
  { code: "TH", name: "Thailand", currency: "THB", symbol: "฿", phoneCode: "66", timezone: "Asia/Bangkok" },
  { code: "TN", name: "Tunisia", currency: "TND", symbol: "د.ت", phoneCode: "216", timezone: "Africa/Tunis" },
  { code: "TR", name: "Turkey", currency: "TRY", symbol: "₺", phoneCode: "90", timezone: "Europe/Istanbul" },
  { code: "UA", name: "Ukraine", currency: "UAH", symbol: "₴", phoneCode: "380", timezone: "Europe/Kyiv" },
  { code: "AE", name: "United Arab Emirates", currency: "AED", symbol: "د.إ", phoneCode: "971", timezone: "Asia/Dubai" },
  { code: "GB", name: "United Kingdom", currency: "GBP", symbol: "£", phoneCode: "44", timezone: "Europe/London" },
  { code: "US", name: "United States", currency: "USD", symbol: "$", phoneCode: "1", timezone: "America/New_York" },
  { code: "UY", name: "Uruguay", currency: "UYU", symbol: "$U", phoneCode: "598", timezone: "America/Montevideo" },
  { code: "UZ", name: "Uzbekistan", currency: "UZS", symbol: "so'm", phoneCode: "998", timezone: "Asia/Tashkent" },
  { code: "VE", name: "Venezuela", currency: "VES", symbol: "Bs.S", phoneCode: "58", timezone: "America/Caracas" },
  { code: "VN", name: "Vietnam", currency: "VND", symbol: "₫", phoneCode: "84", timezone: "Asia/Ho_Chi_Minh" },
  { code: "YE", name: "Yemen", currency: "YER", symbol: "﷼", phoneCode: "967", timezone: "Asia/Aden" },
  { code: "ZW", name: "Zimbabwe", currency: "ZWL", symbol: "Z$", phoneCode: "263", timezone: "Africa/Harare" },
].sort((a, b) => a.name.localeCompare(b.name));
