export const timezones = [
  { value: "UTC", label: "UTC (Coordinated Universal Time)" },
  { value: "Africa/Cairo", label: "Cairo, Egypt (GMT+2)" },
  { value: "Africa/Johannesburg", label: "Johannesburg, South Africa (GMT+2)" },
  { value: "Africa/Lagos", label: "Lagos, Nigeria (GMT+1)" },
  { value: "Africa/Nairobi", label: "Nairobi, Kenya (GMT+3)" },
  { value: "America/Anchorage", label: "Anchorage, USA (AKDT/GMT-8)" },
  { value: "America/Argentina/Buenos_Aires", label: "Buenos Aires, Argentina (ART/GMT-3)" },
  { value: "America/Bogota", label: "Bogota, Colombia (COT/GMT-5)" },
  { value: "America/Chicago", label: "Chicago, USA (CDT/GMT-5)" },
  { value: "America/Denver", label: "Denver, USA (MDT/GMT-6)" },
  { value: "America/Los_Angeles", label: "Los Angeles, USA (PDT/GMT-7)" },
  { value: "America/Mexico_City", label: "Mexico City, Mexico (CST/GMT-6)" },
  { value: "America/New_York", label: "New York, USA (EDT/GMT-4)" },
  { value: "America/Phoenix", label: "Phoenix, USA (MST/GMT-7)" },
  { value: "America/Sao_Paulo", label: "Sao Paulo, Brazil (BRT/GMT-3)" },
  { value: "America/Toronto", label: "Toronto, Canada (EDT/GMT-4)" },
  { value: "America/Vancouver", label: "Vancouver, Canada (PDT/GMT-7)" },
  { value: "Asia/Bangkok", label: "Bangkok, Thailand (ICT/GMT+7)" },
  { value: "Asia/Dubai", label: "Dubai, UAE (GST/GMT+4)" },
  { value: "Asia/Hong_Kong", label: "Hong Kong, China (HKT/GMT+8)" },
  { value: "Asia/Jakarta", label: "Jakarta, Indonesia (WIB/GMT+7)" },
  { value: "Asia/Jerusalem", label: "Jerusalem, Israel (IDT/GMT+3)" },
  { value: "Asia/Kolkata", label: "Kolkata, India (IST/GMT+5:30)" },
  { value: "Asia/Riyadh", label: "Riyadh, Saudi Arabia (AST/GMT+3)" },
  { value: "Asia/Seoul", label: "Seoul, South Korea (KST/GMT+9)" },
  { value: "Asia/Shanghai", label: "Shanghai, China (CST/GMT+8)" },
  { value: "Asia/Singapore", label: "Singapore (SGT/GMT+8)" },
  { value: "Asia/Tokyo", label: "Tokyo, Japan (JST/GMT+9)" },
  { value: "Atlantic/Reykjavik", label: "Reykjavik, Iceland (GMT)" },
  { value: "Australia/Adelaide", label: "Adelaide, Australia (ACST/GMT+9:30)" },
  { value: "Australia/Brisbane", label: "Brisbane, Australia (AEST/GMT+10)" },
  { value: "Australia/Darwin", label: "Darwin, Australia (ACST/GMT+9:30)" },
  { value: "Australia/Melbourne", label: "Melbourne, Australia (AEST/GMT+10)" },
  { value: "Australia/Perth", label: "Perth, Australia (AWST/GMT+8)" },
  { value: "Australia/Sydney", label: "Sydney, Australia (AEST/GMT+10)" },
  { value: "Europe/Amsterdam", label: "Amsterdam, Netherlands (CEST/GMT+2)" },
  { value: "Europe/Athens", label: "Athens, Greece (EEST/GMT+3)" },
  { value: "Europe/Berlin", label: "Berlin, Germany (CEST/GMT+2)" },
  { value: "Europe/Brussels", label: "Brussels, Belgium (CEST/GMT+2)" },
  { value: "Europe/Budapest", label: "Budapest, Hungary (CEST/GMT+2)" },
  { value: "Europe/Dublin", label: "Dublin, Ireland (IST/GMT+1)" },
  { value: "Europe/Helsinki", label: "Helsinki, Finland (EEST/GMT+3)" },
  { value: "Europe/Istanbul", label: "Istanbul, Turkey (TRT/GMT+3)" },
  { value: "Europe/Lisbon", label: "Lisbon, Portugal (WEST/GMT+1)" },
  { value: "Europe/London", label: "London, UK (BST/GMT+1)" },
  { value: "Europe/Madrid", label: "Madrid, Spain (CEST/GMT+2)" },
  { value: "Europe/Moscow", label: "Moscow, Russia (MSK/GMT+3)" },
  { value: "Europe/Oslo", label: "Oslo, Norway (CEST/GMT+2)" },
  { value: "Europe/Paris", label: "Paris, France (CEST/GMT+2)" },
  { value: "Europe/Prague", label: "Prague, Czech Republic (CEST/GMT+2)" },
  { value: "Europe/Rome", label: "Rome, Italy (CEST/GMT+2)" },
  { value: "Europe/Stockholm", label: "Stockholm, Sweden (CEST/GMT+2)" },
  { value: "Europe/Vienna", label: "Vienna, Austria (CEST/GMT+2)" },
  { value: "Europe/Warsaw", label: "Warsaw, Poland (CEST/GMT+2)" },
  { value: "Europe/Zurich", label: "Zurich, Switzerland (CEST/GMT+2)" },
  { value: "Pacific/Auckland", label: "Auckland, New Zealand (NZST/GMT+12)" },
  { value: "Pacific/Fiji", label: "Fiji (FJT/GMT+12)" },
  { value: "Pacific/Honolulu", label: "Honolulu, USA (HST/GMT-10)" },
];
